language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t omarsafwany/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omarsafwany/react-test npm run test -- --coverage

after_success:
  - docker build -t omarsafwany/multi-client ./client
  - docker build -t omarsafwany/multi-nginx ./nginx
  - docker build -t omarsafwany/multi-server ./server
  - docker build -t omarsafwany/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the above images and push them to docker hub
  - docker push omarsafwany/multi-client
  - docker push omarsafwany/multi-nginx
  - docker push omarsafwany/multi-server
  - docker push omarsafwany/multi-worker