version: 2.1

jobs:
  build-docker-test-image:
    working_directory: /app
    docker:
      - image: cimg/node:16.10
    steps:
      - run:
          name: Building Docker test image
          command: docker build -t omarsafwany/react-test -f ./client/Dockerfile.dev ./client

workflows:
  sample:
    jobs:
      - build-docker-test-image